name: Selenium Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  selenium-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Selenium tests
      run: |
        pytest tests/selenium